-- G-SCM 전환 작업 추적용 테이블. RPLS_ADM 스키마에 생성.
-- tracking/conversion-verification.csv(사람이 보는 표)와 같은 정보를 다루되,
-- chatui 변환기가 발견한 이슈(문법 오류 등)를 실행할 때마다 자동으로 쌓을 수 있게 한다.
-- CLAUDE.md 원칙: 이건 우리 도구 자체의 메타데이터 테이블이지 G-SCM 업무 스키마가 아니다 -
-- 기존 AS-IS 테이블은 절대 건드리지 않는다.

-- 화면 1개에 대응하는 AS-IS 파일 1개(및 DTO/메시지 같은 파생 산출물)의 변환 상태.
CREATE TABLE CONV_FILE (
    FILE_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCREEN_ID         VARCHAR2(30)  NOT NULL,
    AS_IS_LAYER       VARCHAR2(20)  NOT NULL,          -- P(JAVA), P(BIZUNIT), F(JAVA), F(BIZUNIT), D(JAVA), D(BIZUNIT), XSQL, DERIVED
    AS_IS_FILENAME    VARCHAR2(200),
    AS_IS_PATH        VARCHAR2(500),
    TOBE_FILENAME     VARCHAR2(200),
    TOBE_PATH         VARCHAR2(500),
    PARSE_STATUS      VARCHAR2(20)  DEFAULT 'UNKNOWN', -- OK, FAIL, NA, UNKNOWN
    COMPILE_STATUS    VARCHAR2(20)  DEFAULT 'UNKNOWN', -- OK, FAIL, NA, UNKNOWN
    CONVERSION_METHOD VARCHAR2(50),                    -- RULE_BASED, LLM_PORTED, RULE_AND_LLM, MANUAL
    TRACK             VARCHAR2(20)  DEFAULT 'UNDECIDED', -- REFACTOR, REIMAGINE, UNDECIDED
    CONVERSION_STATUS VARCHAR2(20)  DEFAULT 'NOT_STARTED', -- NOT_STARTED, IN_PROGRESS, DONE, BLOCKED
    BUILD_CHECK       VARCHAR2(20)  DEFAULT 'NOT_RUN', -- PASS, FAIL, NOT_RUN, NA
    AS_IS_CONTENT_HASH VARCHAR2(64),                    -- SHA-256(AS-IS 원본 내용) - 재실행 시 스킵 캐싱용
    DIFF_TEST_CHECK   VARCHAR2(20)  DEFAULT 'NOT_RUN', -- PASS, FAIL, NOT_RUN, NA
    HUMAN_EDIT_RATIO  NUMBER(5,2),                      -- % (자동 생성 대비 사람이 수정한 라인 비율), 측정 전엔 NULL
    REVIEW_STATUS     VARCHAR2(20)  DEFAULT 'UNREVIEWED', -- UNREVIEWED, IN_REVIEW, APPROVED
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_CONV_FILE UNIQUE (SCREEN_ID, AS_IS_LAYER, AS_IS_FILENAME)
);

-- 변환 시도 중 발견된 개별 이슈. 파일 하나에 여러 건 가능(1:N).
-- chatui/converters.py의 ConversionIssue, chatui/skeleton_gen.py의 SkeletonResult.issues와 1:1 대응.
CREATE TABLE CONV_ISSUE (
    ISSUE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_ID         NUMBER NOT NULL,
    ISSUE_TYPE      VARCHAR2(40)  NOT NULL,  -- XML_PARSE_ERROR, JAVA_COMPILE_ERROR, TAG_MISMATCH,
                                              -- UNSUPPORTED_TAG, REMAPRESULTS_DROPPED, CDATA_SIMPLIFIED,
                                              -- MISSING_STATEMENT, NCTRID_MAP_EMPTY, DELEGATE_CALL_NOT_FOUND,
                                              -- NO_METHODS_FOUND, MISSING_INPUT_FILE ...
    SEVERITY        VARCHAR2(10)  NOT NULL,  -- BLOCKER, WARNING, INFO
    LINE_NO         NUMBER,
    MESSAGE         VARCHAR2(4000),
    DETECTED_BY     VARCHAR2(100),           -- 'chatui/converters.py', 'chatui/skeleton_gen.py', 'manual review' 등
    DETECTED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLVED_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    RESOLVED_AT     TIMESTAMP,
    RESOLUTION_NOTE VARCHAR2(4000),
    CONSTRAINT FK_CONV_ISSUE_FILE FOREIGN KEY (FILE_ID) REFERENCES CONV_FILE(FILE_ID),
    CONSTRAINT CK_CONV_ISSUE_SEVERITY CHECK (SEVERITY IN ('BLOCKER','WARNING','INFO')),
    CONSTRAINT CK_CONV_ISSUE_RESOLVED CHECK (RESOLVED_YN IN ('Y','N'))
);

CREATE INDEX IX_CONV_ISSUE_FILE ON CONV_ISSUE(FILE_ID);
CREATE INDEX IX_CONV_FILE_SCREEN ON CONV_FILE(SCREEN_ID);
